name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    name: Build and analyze on SonarCloud
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Adjust this to your project's version

      - name: Install SonarScanner for MSBuild
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarCloud analysis
        run: dotnet-sonarscanner begin /k:"myorganizationsite_InternationalBankAPI" /o:"myorganizationsite" /d:sonar.login=${{ secrets.SONAR_TOKEN }}
      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore

      - name: End SonarCloud analysis
        run: dotnet-sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
